import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";

import type { StateService } from "../../../02-supporting-services/types.js";
import type { CalendarEvent } from "../../../02-supporting-services/04-topic-profile-service/04.01-calendar/types.js";
import type { CalDAVCollectionMetadata, CalDAVEvent } from "./types.js";

const DAV_HEADER = "1, calendar-access";

const COLLECTION_METADATA: CalDAVCollectionMetadata = {
  display_name: "Family Command Center Calendar",
  description: "Read-only calendar feed generated by Family Command Center.",
  timezone: "UTC",
  ctag: "1",
};

export interface CalDavServiceOptions {
  state_service: StateService;
}

export class CalDavService {
  private readonly stateService: StateService;

  public constructor(options: CalDavServiceOptions) {
    this.stateService = options.state_service;
  }

  public registerRoutes(fastify: FastifyInstance): void {
    fastify.options("/caldav", async (_request, reply) => {
      this.replyOptions(reply);
      reply.code(204);
      return null;
    });

    fastify.options("/caldav/*", async (_request, reply) => {
      this.replyOptions(reply);
      reply.code(204);
      return null;
    });

    fastify.route({
      method: "PROPFIND",
      url: "/caldav",
      handler: async (_request, reply) => {
        const events = await this.getCalDavEvents();
        reply
          .header("Content-Type", "application/xml; charset=utf-8")
          .header("DAV", DAV_HEADER)
          .send(this.propfindResponse(events));
      },
    });

    fastify.route({
      method: "REPORT",
      url: "/caldav",
      handler: async (_request, reply) => {
        const events = await this.getCalDavEvents();
        reply
          .header("Content-Type", "application/xml; charset=utf-8")
          .header("DAV", DAV_HEADER)
          .send(this.reportResponse(events));
      },
    });

    fastify.get("/caldav/events/:eventId.ics", async (request, reply) => {
      const params = request.params as { eventId: string };
      const events = await this.getCalDavEvents();
      const event = events.find((candidate) => candidate.source_event_id === params.eventId);
      if (!event) {
        reply.code(404);
        return { error: "Not found" };
      }

      reply.header("Content-Type", "text/calendar; charset=utf-8");
      return this.renderVCalendar([event]);
    });

    const rejectWrites = async (_request: FastifyRequest, reply: FastifyReply) => {
      this.replyOptions(reply);
      reply.code(405);
      return { error: "Read-only endpoint" };
    };

    fastify.route({ method: "PUT", url: "/caldav/*", handler: rejectWrites });
    fastify.route({ method: "POST", url: "/caldav/*", handler: rejectWrites });
    fastify.route({ method: "PATCH", url: "/caldav/*", handler: rejectWrites });
    fastify.route({ method: "DELETE", url: "/caldav/*", handler: rejectWrites });
  }

  private replyOptions(reply: FastifyReply): void {
    reply
      .header("Allow", "OPTIONS, PROPFIND, REPORT, GET")
      .header("DAV", DAV_HEADER)
      .header("MS-Author-Via", "DAV");
  }

  private async getCalDavEvents(): Promise<CalDAVEvent[]> {
    const state = await this.stateService.getSystemState();
    return state.calendar.events.map((event) => this.toCalDavEvent(event));
  }

  private toCalDavEvent(event: CalendarEvent): CalDAVEvent {
    return {
      uid: `fcc-${event.id}@local`,
      summary: event.title,
      dtstart: event.date_start ?? event.date ?? event.created_at,
      dtend: event.date_end,
      location: event.location ?? undefined,
      description: `Topic: ${event.topic}; Status: ${event.status}`,
      source_event_id: event.id,
    };
  }

  private propfindResponse(events: CalDAVEvent[]): string {
    const eventResponses = events
      .map(
        (event) => `
  <d:response>
    <d:href>/caldav/events/${event.source_event_id}.ics</d:href>
    <d:propstat>
      <d:prop>
        <d:getetag>"${event.uid}"</d:getetag>
        <d:getcontenttype>text/calendar; charset=utf-8</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>`,
      )
      .join("");

    return `<?xml version="1.0" encoding="utf-8" ?>
<d:multistatus xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
  <d:response>
    <d:href>/caldav</d:href>
    <d:propstat>
      <d:prop>
        <d:displayname>${COLLECTION_METADATA.display_name}</d:displayname>
        <cs:getctag>${COLLECTION_METADATA.ctag}</cs:getctag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>${eventResponses}
</d:multistatus>`;
  }

  private reportResponse(events: CalDAVEvent[]): string {
    const entries = events
      .map(
        (event) => `
  <d:response>
    <d:href>/caldav/events/${event.source_event_id}.ics</d:href>
    <d:propstat>
      <d:prop>
        <cal:calendar-data xmlns:cal="urn:ietf:params:xml:ns:caldav">${this.escapeXml(
          this.renderVCalendar([event]),
        )}</cal:calendar-data>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>`,
      )
      .join("");

    return `<?xml version="1.0" encoding="utf-8" ?>
<d:multistatus xmlns:d="DAV:">${entries}
</d:multistatus>`;
  }

  private renderVCalendar(events: CalDAVEvent[]): string {
    const renderedEvents = events.map((event) => this.renderVEvent(event)).join("\r\n");
    return [
      "BEGIN:VCALENDAR",
      "PRODID:-//FCCv2//Family Command Center//EN",
      "VERSION:2.0",
      "CALSCALE:GREGORIAN",
      renderedEvents,
      "END:VCALENDAR",
    ].join("\r\n");
  }

  private renderVEvent(event: CalDAVEvent): string {
    const lines = [
      "BEGIN:VEVENT",
      `UID:${event.uid}`,
      `DTSTAMP:${this.toIcalDate(new Date())}`,
      `DTSTART:${this.toIcalDate(event.dtstart)}`,
      event.dtend ? `DTEND:${this.toIcalDate(event.dtend)}` : undefined,
      `SUMMARY:${this.escapeIcs(event.summary)}`,
      event.description ? `DESCRIPTION:${this.escapeIcs(event.description)}` : undefined,
      event.location ? `LOCATION:${this.escapeIcs(event.location)}` : undefined,
      "END:VEVENT",
    ].filter((line): line is string => Boolean(line));

    return lines.join("\r\n");
  }

  private toIcalDate(value: Date): string {
    return value.toISOString().replace(/[-:]/gu, "").replace(".000", "");
  }

  private escapeIcs(value: string): string {
    return value.replace(/\\/gu, "\\\\").replace(/\n/gu, "\\n").replace(/,/gu, "\\,");
  }

  private escapeXml(value: string): string {
    return value
      .replace(/&/gu, "&amp;")
      .replace(/</gu, "&lt;")
      .replace(/>/gu, "&gt;")
      .replace(/"/gu, "&quot;")
      .replace(/'/gu, "&apos;");
  }
}

export function createCalDavService(options: CalDavServiceOptions): CalDavService {
  return new CalDavService(options);
}
